'use client';
import React from 'react';
import { Button } from '../ui/button';

const DownloadSummaryButton = ({
  title,
  summary_text,
  fileName,
  createdAt,
}: {
  title: string;
  summary_text: string;
  fileName: string;
  createdAt: string;
}) => {
  const handleDownload = () => {
    const summaryContent = `
# ${title}
Generated Summary
Generaetd on: ${new Date(createdAt).toLocaleDateString()}


${summary_text}

original File : ${fileName}
Generated by Summaire-AI Powered App
    `;

    const blob = new Blob([summaryContent], {
      type: '/text/plain',
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };
  return (
    <Button
      size={'sm'}
      className="h-8 px-3 bg-rose-100 text-rose-600 hover:text-rose-700 hover:bg-rose-50"
      onClick={handleDownload}
    >
      Download Summary
    </Button>
  );
};

export default DownloadSummaryButton;
